//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetBoom.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int IdMatch { get; set; }
        public int IdTeamOne { get; set; }
        public int IdTeamTwo { get; set; }
        public int IdSport { get; set; }
        public int Coefficient { get; set; }
    
        public virtual Sport Sport { get; set; }
        public virtual TeamOne TeamOne { get; set; }
        public virtual TeamTwo TeamTwo { get; set; }
    }
}
