//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetBoom.DataFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        private static DBEntities context;
        public DBEntities()
            : base("name=DBEntities")
        {
        }
        public static DBEntities GetContext()
        {
            if (context == null)
                context = new DBEntities();
            return context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Match> Match { get; set; }
        public virtual DbSet<Refills> Refills { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sport> Sport { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TeamOne> TeamOne { get; set; }
        public virtual DbSet<TeamTwo> TeamTwo { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
